## Local url
@url = http://localhost:3000/gpt

### Call the Open AI API orthography check use case
POST {{url}}/orthography-check
content-type: application/json

{
  "prompt": "Las casa son mui bonitas"
}

### Call the Open AI API Pros Cons Discusser use case
POST {{url}}/pros-cons-discusser
content-type: application/json

{
  "prompt": "¿Puedes comparar entre un cocher o una moto?"
}


### Call the Open AI API Pros Cons Stream use case
POST {{url}}/pros-cons-discusser-stream
content-type: application/json

{
  "prompt": "¿Puedes comparar entre un cocher o una moto?"
}

### Call the Open AI API translate use case
POST {{url}}/translate
content-type: application/json

{
  "prompt": "Es un placer conocerte, ¿puedes indicarme dónde encuentro la estación de bus más cercana?",
  "lang": "árabe"
}

### Call the Open AI API text to audio use case
POST {{url}}/text-to-audio
content-type: application/json

{
  "prompt": "Mi nombre es Juan Pablo Perez",
  "voice": "alloy"
}

### Get an audio already generated
GET {{url}}/text-to-audio/1729919179808