## Local url
@url = http://localhost:3000/gpt

### Call the Open AI API orthography check use case
POST {{url}}/orthography-check
content-type: application/json

{
  "prompt": "Las casa son mui bonitas"
}

### Call the Open AI API Pros Cons Discusser use case
POST {{url}}/pros-cons-discusser
content-type: application/json

{
  "prompt": "¿Puedes comparar entre un cocher o una moto?"
}


### Call the Open AI API Pros Cons Stream use case
POST {{url}}/pros-cons-discusser-stream
content-type: application/json

{
  "prompt": "¿Puedes comparar entre un cocher o una moto?"
}

### Call the Open AI API translate use case
POST {{url}}/translate
content-type: application/json

{
  "prompt": "Es un placer conocerte, ¿puedes indicarme dónde encuentro la estación de bus más cercana?",
  "lang": "árabe"
}

### Call the Open AI API text to audio use case
POST {{url}}/text-to-audio
content-type: application/json

{
  "prompt": "Mi nombre es Juan Pablo Perez",
  "voice": "alloy"
}

### Get an audio already generated
GET {{url}}/text-to-audio/1729919179808


### Call the Open AI API audio to text use case
POST {{url}}/audio-to-text
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="ElParque.m4a"
Content-Type: audio/m4a

< ./ElParque.m4a
--MfnBoundry
Content-Disposition: form-data; name="prompt"

mantén todos los signos de puntuación y humms... y ahs...
--MfnBoundry--

### Call the Open AI API image generation use case
POST {{url}}/image-generation
content-type: application/json

{
  "prompt": "Necesito generar una imagen el estadio metropolitano del atlético de madrid con el público celebrando un gol"
}

### Get an image already generated
GET {{url}}/image-generation/1731301499804.png

### Call the Open AI API image variation use case
POST {{url}}/image-variation
content-type: application/json

{
  "baseImage": "http://localhost:3000/gpt/image-generation/1731304641822.png"
}

### Call the Open AI API audio to text use case
POST {{url}}/extract-text-from-image
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="file"; filename="dogs-9172481_1280.jpg"
Content-Type: image/*

< ./dogs-9172481_1280.jpg
--MfnBoundry
Content-Disposition: form-data; name="prompt"

describe la imagen
--MfnBoundry--